#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# 
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: |
  This lesson is build with a custom workbench.
  It is designed as a proof of concept of "flavored" lesson feature.
  In other words, the idea of building multiple versions of lesson from
  the same episode markdown. This feature is **not** yet implimented
  in mainline workbench. It is very much a work in progress idea.

# Overall title for pages.
title: 'Flavored Lesson Demo'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2025-08-26

# Comma-separated list of keywords for the lesson
keywords: 'workbench, sandpaper, varnish, proof-of-concept'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/katrinabrock/flavor-demo'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'kbrock@ab.mpg.de'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

flavors:
  r-flavor:
    title: R
    render: yes
  python-flavor:
    title: Python
    render: yes

# Order of episodes in your lesson
  
episodes: 
- 01_introduction.md
- 02_r_only.md
- 02_py_only.md

# Information for Learners
learners: 

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live

sandpaper: katrinabrock/sandpaper@flavors
varnish: katrinabrock/varnish@flavors


